### PR TITLE
fix(mpi): make `mpi::send` w/ implicit ExecSpace directly call explicit overload 

### LINKED ISSUE #174: mpi: `send` with implicit ExecSpace does not observe the specified comm mode
Our implementation of `KokkosComm::mpi::send` without a `KokkosExecutionSpace` template parameter does not observe the specified `CommunicationMode`:
https://github.com/kokkos/kokkos-comm/blob/45aa5e02d8beb47d4a04a8b3b29d2d33cc09e4ed/src/KokkosComm/mpi/send.hpp#L32-L56

We should use the `mpi_send_fn` variable defined above, which selects the MPI call corresponding to the specified communication mode, rather than calling `MPI_Send` directly.

Alternatively, we could call the version with an explicit `KokkosExecutionSpace` and construct the default ExecSpace in place.

### PR DESCRIPTION
**Pull request by dssgabriel**
This PR closes #174 by modifying the `KokkosComm::mpi::send` overload, which previously did not take an explicit `ExecSpace` template parameter, to directly invoke the fully explicit implementation, passing a `Kokkos::DefaultExecutionSpace` argument.

This effectively removes the bug noted in the above-mentioned issue, where this overload did not observe the Communication Mode requested by the user at the function call level.

### CODE REVIEW

File: src/KokkosComm/mpi/send.hpp [hunk 1]
```diff
@@ -29,60 +29,30 @@
...
     }
   };
 
-  if (KokkosComm::is_contiguous(sv)) {
-    using SendScalar = typename SendView::value_type;
-    space.fence("fence before MPI_Send");
-    mpi_send_fn(KokkosComm::data_handle(sv), KokkosComm::span(sv), KokkosComm::Impl::mpi_type_v<SendScalar>, dest, tag,
-                comm);
+  if (is_contiguous(sv)) {
+    mpi_send_fn(data_handle(sv), span(sv), Impl::mpi_type_v<T>);
```
Comment (cedricchevalier19) [inline src/KokkosComm/mpi/send.hpp:39]: Why `fence()` is not used here?

It looks inconsistent with the previous implementation and the other branch.

**Review by cedricchevalier19 — CHANGES_REQUESTED** [review]
Check for `fence()` consistency.

File: src/KokkosComm/mpi/send.hpp (hunk 1 above)
Comment (dssgabriel) [reply src/KokkosComm/mpi/send.hpp:39]: On the non-contiguous path, we fence after the view packing because this may allocate some data and we need to ensure that the view is ready before calling MPI with it.

Because we don't have the packing operation in the contiguous branch I don't think the fence was necessary, hence I removed it.

Comment (cedricchevalier19) [reply src/KokkosComm/mpi/send.hpp:39]: I think other part of KokkosComm fences because it is kind of expected that you are viewed as added to the queue of the execution space. We fence to ensure that the buffer is ready to be used in a MPI context.

Note that it is on this kind of call that NCCL is interesting, being simply added to the execution queue.

Comment (dssgabriel) [reply src/KokkosComm/mpi/send.hpp:39]: Yes, this also goes back to what we previously discussed in #108. I am putting the `fence()` back. :+1:

File: src/KokkosComm/mpi/send.hpp [hunk 2]
```diff
@@ -93,4 +64,9 @@ void send(const ExecSpace &space, const SendView &sv, int dest, int tag, MPI_Com
   send(space, sv, dest, tag, comm, DefaultCommMode{});
 }
 
+template <KokkosView SendView>
+void send(const SendView &sv, int dest, int tag, MPI_Comm comm) {
```
Comment (cedricchevalier19) [inline src/KokkosComm/mpi/send.hpp:56]: Add a comment that a side effect is to perform a fence on the default execution space.

**Review by cedricchevalier19 — DISMISSED** [review]
Thanks!

**Comment by dssgabriel** [comment]
@cwpearson It looks like you need to add back the SNL label on this PR so it can run on the SNL CI?

**Review by cedricchevalier19 — APPROVED** [review]
